# Generated by Django 3.1.7 on 2021-03-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ai', 'AI'), ('crypto', 'CRYPTO'), ('capitalism', 'CAPITALISM'), ('creative writing', 'CREATIVE WRITING')], default='ai', max_length=20),
        ),
    ]
